run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - promlinter
    - revive
    - staticcheck
    - unconvert
    - unused

linters-settings:
  goimports:
    local-prefixes: k8s.io/kube-state-metrics,k8s.io/kube-state-metrics/v2

issues:
  exclude-use-default: false
  exclude-rules:
    # We don't check metrics naming in the tests.
    - path: _test\.go
      linters:
        - promlinter
    # TODO(mrueg) Improve error handling
    - text: "G104:"
      linters:
        - gosec
    - text: "package-comments:"
      linters:
        - revive
