version: 2

snapshot:
  version_template: "snapshot"

builds:
  - id: kube-state-metrics
    main: .
    binary: kube-state-metrics
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Tag}}
      - -X github.com/prometheus/common/version.Revision={{.ShortCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X k8s.io/kube-state-metrics/v2/pkg/app.ClientGoVersion={{ index .Env "K8S_CLIENT_VERSION" }}

kos:
  - 
    id: kube-state-metrics
    build: kube-state-metrics
    repositories:
      - gcr.io/k8s-staging-kube-state-metrics/kube-state-metrics
    base_image: gcr.io/distroless/static-debian13:nonroot
    # In snapshot mode, ko publishes to the local Docker daemon using this domain.
    local_domain: "registry.k8s.io/kube-state-metrics/kube-state-metrics"
    platforms:
      - linux/amd64
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
    tags:
      - "{{.Tag}}"
      - '{{if not .IsSnapshot}}latest{{end}}'
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"
    bare: true

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  use: github
  sort: asc
  groups:
    - title: "Features"
      regexp: "(?i)(feat|feature|\\[feature\\]|\\[feat\\]|\\bFEATURE\\b)"
      order: 1
    - title: "Bug Fixes"  
      regexp: "(?i)(fix|bugfix|\\[bugfix\\]|\\[BUGFIX\\]|\\bBUGFIX\\b)"
      order: 2
    - title: "Documentation"
      regexp: "(?i)(docs?|documentation|\\[docs?\\])"
      order: 3
    - title: "Dependencies"
      regexp: "(?i)(build\\(deps\\)|bump|dependencies)"
      order: 4
    - title: "Maintenance"
      regexp: "(?i)(chore|refactor|\\[chore\\])"
      order: 5
    - title: "Other Changes"
      regexp: ".*"
      order: 99

  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'merge conflict'
      - 'Merge branch'
      - 'Merge pull request'

release:
  github:
    owner: kubernetes     
    name: kube-state-metrics      

  prerelease: "true"

  header: |
    ## {{ .Tag }} / {{ .Now.Format "2006-01-02" }}
    
    {{- if index .Env "GO_VERSION" }}
    ## Note
    - This release builds with Go `{{ index .Env "GO_VERSION" }}`
    {{- end }}

    {{- if index .Env "K8S_CLIENT_VERSION" }}
    - This release builds with `k8s.io/client-go`: `{{ index .Env "K8S_CLIENT_VERSION" }}`
    {{- end }}

    {{- if index .Env "GITHUB_ACTOR" }}
    - Release coordinator: @{{ index .Env "GITHUB_ACTOR" }}
    {{- end }}

  footer: |
    **Full Changelog**: {{ .GitURL }}/compare/{{ .PreviousTag }}...{{ .Tag }}

  mode: replace
  
  # If set, will create a release discussion in the category specified.
  # Warning: do not use categories in the 'Announcement' format.
  # Check https://github.com/goreleaser/goreleaser/issues/2304 for more info.
  # Default: ''.
  discussion_category_name: Releases
