# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 2700s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20241111-71c32dbdcc'
    entrypoint: make
    env:
    - TAG=$_PULL_BASE_REF
    - GIT_COMMIT=$_PULL_BASE_SHA
    args:
    - push
