/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "k8s.io/kube-state-metrics/v2/pkg/customresourcemonitor/apis/customresourcemonitor/v1alpha1"
)

// FakeCustomResourceMonitors implements CustomResourceMonitorInterface
type FakeCustomResourceMonitors struct {
	Fake *FakeCustomresourceV1alpha1
	ns   string
}

var customresourcemonitorsResource = v1alpha1.SchemeGroupVersion.WithResource("customresourcemonitors")

var customresourcemonitorsKind = v1alpha1.SchemeGroupVersion.WithKind("CustomResourceMonitor")

// Get takes name of the customResourceMonitor, and returns the corresponding customResourceMonitor object, and an error if there is any.
func (c *FakeCustomResourceMonitors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CustomResourceMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customresourcemonitorsResource, c.ns, name), &v1alpha1.CustomResourceMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomResourceMonitor), err
}

// List takes label and field selectors, and returns the list of CustomResourceMonitors that match those selectors.
func (c *FakeCustomResourceMonitors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomResourceMonitorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customresourcemonitorsResource, customresourcemonitorsKind, c.ns, opts), &v1alpha1.CustomResourceMonitorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomResourceMonitorList{ListMeta: obj.(*v1alpha1.CustomResourceMonitorList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomResourceMonitorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customResourceMonitors.
func (c *FakeCustomResourceMonitors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customresourcemonitorsResource, c.ns, opts))

}

// Create takes the representation of a customResourceMonitor and creates it.  Returns the server's representation of the customResourceMonitor, and an error, if there is any.
func (c *FakeCustomResourceMonitors) Create(ctx context.Context, customResourceMonitor *v1alpha1.CustomResourceMonitor, opts v1.CreateOptions) (result *v1alpha1.CustomResourceMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customresourcemonitorsResource, c.ns, customResourceMonitor), &v1alpha1.CustomResourceMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomResourceMonitor), err
}

// Update takes the representation of a customResourceMonitor and updates it. Returns the server's representation of the customResourceMonitor, and an error, if there is any.
func (c *FakeCustomResourceMonitors) Update(ctx context.Context, customResourceMonitor *v1alpha1.CustomResourceMonitor, opts v1.UpdateOptions) (result *v1alpha1.CustomResourceMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customresourcemonitorsResource, c.ns, customResourceMonitor), &v1alpha1.CustomResourceMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomResourceMonitor), err
}

// Delete takes name of the customResourceMonitor and deletes it. Returns an error if one occurs.
func (c *FakeCustomResourceMonitors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(customresourcemonitorsResource, c.ns, name, opts), &v1alpha1.CustomResourceMonitor{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomResourceMonitors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customresourcemonitorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomResourceMonitorList{})
	return err
}

// Patch applies the patch and returns the patched customResourceMonitor.
func (c *FakeCustomResourceMonitors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomResourceMonitor, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customresourcemonitorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CustomResourceMonitor{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomResourceMonitor), err
}
