name: openvex

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag to generate the OpenVEX document for and attach it to
        required: true
        type: string
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  vexctl:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name || inputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ env.RELEASE_VERSION }}
          persist-credentials: false

      - uses: openvex/generate-vex@c59881b41451d7ccba5c3b74cd195382b8971fcd
        # Refer: https://github.com/openvex/vexctl#operational-model
        name: Run vexctl
        with:
            product: pkg:golang/k8s.io/kube-state-metrics/v2@${{ env.RELEASE_VERSION }}
            file: kube-state-metrics.openvex.json

      - name: Upload OpenVEX document to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$RELEASE_VERSION" kube-state-metrics.openvex.json
